name: build_deploy_staging_poi_api_CI
on:
  push:
    paths:
      - "apis/poi/**"
      - ".github/workflows/**"
jobs: 
  validate_stage:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    #needs: build_and_staging
    steps:
    - name: curl
      id: poi-health-check
      uses: satak/webrequest-action@master
      with:
        url: https://openhackzjg27yi6poi-staging.azurewebsites.net/api/healthcheck/poi
        method: GET
    - name: Check Output
      shell: pwsh
      run: |
          $output = '${{ steps.poi-health-check.outputs.output }}' | ConvertFrom-Json
          Write-Host " Status code is $($output.statusCode) "
          if($($output.statusCode) -eq 200) {          
            Write-host "Healthy"
            Write-Error "API is not healthy"
            }
          else {
            Write-Host "Not Healthy" }
         
  
