name: build_deploy_staging_poi_api_CI
on:
  push:
    paths:
      - "apis/poi/**"
jobs: 
  validate_stage:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    #needs: build_and_staging
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://openhackzjg27yi6poi-staging.azurewebsites.net/api/healthcheck/poi
  
