name: build_deploy_staging_poi_api_CI
on:
  push:
    paths:
      - "apis/poi/**"
      - ".github/workflows/**"
jobs: 
  validate_stage:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    #needs: build_and_staging
    steps:
    - name: curl      
      uses: satak/webrequest-action@master
      with:
        url: https://openhackzjg27yi6poi-staging.azurewebsites.net/api/healthcheck/poi
    - name: Check Output
      run: |
          $output = '${{ steps.webhook.outputs.output }}' | ConvertFrom-Json
          Write-Host "Health Status is $($output.data.message)"
  
