name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    - name: Install dependencies
      working-directory: apis/poi
      run: dotnet restore
    - name: Build
      working-directory: apis/poi
      run: dotnet build --configuration Release --no-restore
    - name: Test
      id: Test
      working-directory: apis/poi
      run: dotnet test --no-restore --verbosity normal      
    - if: ${{steps.Test.outcome}} == 'failure'
      name: Create Github Issue
      run: 'echo Need a Github Issue'
      
      
