name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    - name: Install dependencies
      working-directory: apis/poi
      run: dotnet restore
    - name: Build
      working-directory: apis/poi
      run: dotnet build --configuration Release --no-restore
    - name: Test
      id: Test
      working-directory: apis/poi
      run: dotnet test --no-restore --verbosity normal      
    - if: ${{ failure() }}
      name: Create Github Issue
      uses: bryannice/gitactions-git-issue-creation@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}
          GITHUB_OWNER: 'sowsan'
          GITHUB_REPO_NAME: 'openhack-devops'
          GITHUB_ISSUE_TITLE: 'Demo''ing Git Issue Creation'
          GITHUB_ISSUE_BODY: 'Demo''ing Git Issue Creation'
      
      
